// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-event-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_event_info_default = defineTool({
  name: "get_event_info",
  title: "Get event info",
  description: "Return key facts about the Dni \u015Awiat\u0142a 2026 conference: edition, date, venue, city, organizers, and registration URL.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Dni \u015Awiat\u0142a 2026",
      edition: "XVIII (18th)",
      tagline: "In\u017Cynieria zwyci\u0119stwa \u2014 technologia na najwy\u017Cszych obrotach",
      date: "2026-10-20",
      venue: "Hotel Novotel Centrum",
      city: "Warsaw, Poland",
      organizers: ["Salumanus", "DCN Europe"],
      audience: "Telco and Data Center professionals",
      website: "https://dniswiatla.pl",
      registration_url: "https://dniswiatla.pl/#rejestracja",
      language: "PL / EN"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/get-agenda.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var AGENDA = [
  { time: "9:00\u201310:00", title: "Otwarcie Dni \u015Awiat\u0142a", speaker: "" },
  { time: "10:00\u201310:25", title: "Jeden bolid, ka\u017Cdy tor. Uniwersalny modu\u0142 optyczny i jego konfiguracja w \u015Brodowisku SRD", speaker: "Salumanus" },
  { time: "10:25\u201310:50", title: "DCN Europe \u2014 Enterprise / Wi-Fi 7 (premiera w maju) / case 100G w DC", speaker: "DCN Europe" },
  { time: "10:50\u201311:15", title: "QKD / kryptografia post-kwantowa \u2014 zabezpieczanie po\u0142\u0105cze\u0144", speaker: "" },
  { time: "11:15\u201311:45", title: "Przerwa kawowa", speaker: "" },
  { time: "11:45\u201312:10", title: "DCN IP/MPLS \u2014 rodzina produkt\xF3w dla operator\xF3w (L2/L3)", speaker: "Raisecom" },
  { time: "12:10\u201312:35", title: "Telekom \u015Bwiadcz\u0105cy Enterprise jako us\u0142uga \u2014 klocki packet-optical", speaker: "" },
  { time: "12:35\u201313:00", title: "Mniej pitstop\xF3w, szybsze okr\u0105\u017Cenie. Multiservice BTS jako w\u0119ze\u0142 agreguj\u0105cy sieci operatora", speaker: "Salumanus" },
  { time: "13:00\u201314:30", title: "Lunch", speaker: "" },
  { time: "14:30\u201315:30", title: "Panel dyskusyjny: \u201EIskander czy totalny blackout? Jak przygotowa\u0107 sie\u0107 na wyzwania geopolityki\u201D", speaker: "\u0141ukasz Dec" },
  { time: "15:30\u201316:00", title: "Przerwa kawowa", speaker: "" },
  { time: "16:00\u201316:25", title: "DCNY - szczeg\xF3\u0142y wkr\xF3tce", speaker: "" },
  { time: "16:25\u201316:50", title: "Zdj\u0105\u0107 balast, doda\u0107 pr\u0119dko\u015B\u0107. Koherentne 100/400/800G i IP over DWDM w praktyce", speaker: "Salumanus" },
  { time: "16:50\u201317:00", title: "KAHOOT i sesja Q&A", speaker: "" },
  { time: "17:00", title: "Rozpocz\u0119cie imprezy w stylu F1", speaker: "" }
];
var get_agenda_default = defineTool2({
  name: "get_agenda",
  title: "Get agenda",
  description: "Return the full session agenda for Dni \u015Awiat\u0142a 2026 with time slots, titles, and speaker/company when known.",
  inputSchema: {
    filter: z.string().optional().describe("Optional case-insensitive substring to match against session title or speaker.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ filter }) => {
    const items = filter ? AGENDA.filter(
      (i) => (i.title + " " + i.speaker).toLowerCase().includes(filter.toLowerCase())
    ) : AGENDA;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { items, count: items.length }
    };
  }
});

// src/lib/mcp/tools/get-speakers.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var SPEAKERS = [
  { name: "Marcin Ba\u0142a", role: "CEO Salumanus", company: "Salumanus" },
  { name: "Andrzej Wojnar", role: "Salumanus", company: "Salumanus" },
  { name: "\u0141ukasz Sukiennik", role: "Salumanus", company: "Salumanus" },
  { name: "Grzegorz Ro\u017A", role: "Salumanus", company: "Salumanus" },
  { name: "\u0141ukasz Dec", role: "Moderator panelu dyskusyjnego", company: "" }
];
var get_speakers_default = defineTool3({
  name: "get_speakers",
  title: "Get speakers",
  description: "Return the list of confirmed speakers for Dni \u015Awiat\u0142a 2026.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(SPEAKERS, null, 2) }],
    structuredContent: { speakers: SPEAKERS, count: SPEAKERS.length }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "dni-swiatla-2026-mcp",
  title: "Dni \u015Awiat\u0142a 2026",
  version: "0.1.0",
  instructions: "Public information tools for the Dni \u015Awiat\u0142a 2026 conference (Salumanus & DCN Europe, 20 October 2026, Warsaw). Use `get_event_info` for date/venue/registration, `get_agenda` for the session schedule (optional keyword filter), and `get_speakers` for the speaker list.",
  tools: [get_event_info_default, get_agenda_default, get_speakers_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
